pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              name: jenkins-agent
            spec:
              containers:
              - name: gradle
                image: gradle:8.5-jdk21-alpine
                command: ["cat"]
                tty: true
              - name: docker
                image: docker:27.2.0-alpine3.20
                command: ["cat"]
                tty: true
                volumeMounts:
                - mountPath: "/var/run/docker.sock"
                  name: docker-socket
              volumes:
              - name: docker-socket
                hostPath:
                  path: "/var/run/docker.sock"
            '''
        }
    }

    environment {
        DOCKER_IMAGE_NAME = 'godbyul/beyondlog-api'
        DOCKER_CREDENTIALS_ID = 'dockerhub-access'
    }

    stages {
        stage('Gradle Build') {
            steps {
                container('gradle') {
                    dir('be-4th-4team-backend') {
                        sh 'chmod +x ./gradlew'
                        // sh './gradlew clean build -x test'
                        sh './gradlew clean bootJar'
                    }
                }
            }
        }

        stage('Image Build & Push') {
            steps {
                container('docker') {
                    dir('be-4th-4team-backend') {
                        script {
                            def dockerImageVersion = "${env.BUILD_NUMBER}"

                            sh 'docker logout'

                            withCredentials([usernamePassword(
                                credentialsId: DOCKER_CREDENTIALS_ID,
                                usernameVariable: 'DOCKER_USERNAME', 
                                passwordVariable: 'DOCKER_PASSWORD'
                                )]) {
                                sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                            }

                            withEnv(["DOCKER_IMAGE_VERSION=${dockerImageVersion}"]) {
                                sh 'docker -v'
                                sh 'echo $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION'
                                sh 'pwd'
                                sh 'ls -al'
                                sh 'docker build --no-cache -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION .'
                                sh 'docker image inspect $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION'
                                sh 'docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION'
                            }
                        }
                    }
                }
            }
        }

        stage('Trigger beyondlog-k8s-manifests') {
            steps {
                script {
                    def dockerImageVersion = "${env.BUILD_NUMBER}"
                    
                    withEnv(["DOCKER_IMAGE_VERSION=${dockerImageVersion}"]) {
                        // 다른 잡을 빌드하면서 파라미터 전달
                        build job: 'beyondlog-k8s-manifests',
                            parameters: [
                                string(name: 'DOCKER_IMAGE_VERSION', value: "${DOCKER_IMAGE_VERSION}")
                            ],
                            wait: true // 하위 잡이 끝날 때까지 기다림
                    }
                }
            }
        }
    }

    post {
        always {
            withCredentials([string(
                credentialsId: 'discord-webhook', 
                variable: 'DISCORD_WEBHOOK_URL'
            )]) {
                discordSend description: """
                제목 : ${currentBuild.displayName}
                결과 : ${currentBuild.result}
                실행 시간 : ${currentBuild.duration / 1000}s
                """,
                result: currentBuild.currentResult,
                title: "${env.JOB_NAME} : ${currentBuild.displayName}", 
                webhookURL: "${DISCORD_WEBHOOK_URL}"
            }
        }
    }
}